#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: ROCm
## @Creation date file: 17.04.2021, 21:20:14

[[ -z "${ROCm_script_source}" ]] && declare -rx ROCm_script_source="$BASH_SOURCE"

if [[ -z "${ROCm_script_source_path}" ]]; then
  temp_one="$(dirname ${ROCm_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx ROCm_script_source_path="$(pwd)"
  else
    declare -rx ROCm_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_ROCm() {

  if [[ ! -f etc/yum.repos.d/ROCm.repo ]]; then
    cat  <<EOF | sudo tee /etc/yum.repos.d/ROCm.repo >/dev/null
[ROCm]
name=ROCm
baseurl=https://repo.radeon.com/rocm/centos8/4.0.1
enabled=1
gpgcheck=1
gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key
skip_if_unavailable=True
EOF
  fi

}

function main_ROCm_script_source() {

  # printf "Initialise main function of ROCm script source\n";

  install_ROCm "$@"

}

main_ROCm_script_source "$@"
