#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: enable-multipath
## @Creation date file: 11.04.2021, 01:00:35

[[ -z "${enable_multipath_script_source}" ]] && declare -rx enable_multipath_script_source="$BASH_SOURCE"

if [[ -z "${enable_multipath_script_source_path}" ]]; then
  temp_one="$(dirname ${enable_multipath_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx enable_multipath_script_source_path="$(pwd)"
  else
    declare -rx enable_multipath_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_enable_multipath() {


  local install_pkg=(
    'iscsi-initiator-utils'
    'device-mapper-multipath'
  )

  pm "$@" -- "${install_pkg[@]}"

  install_pkg=(
    'iscsi'
    'iscsid'
    'multipathd'
  )

  sudo systemctl start "${install_pkg[@]}"
  sudo systemctl enable "${install_pkg[@]}"

  sudo mpathconf --enable --with_multipathd y

  sudo modprobe dm-multipath
  sudo modprobe dm-round-robin
  sudo lsmod | grep dm_

  cat <<EOF
В файле /etc/multipath.conf комментируем строки:
  #blacklist {
  #}
EOF

}

function main_enable_multipath_script_source() {

  # printf "Initialise main function of enable-multipath script source\n";

  local key=
  echo -e "Enable multipath ? (N/y)"
  read key
  case "${key}" in
    Y | y | yes | Yes | YES) install_enable_multipath "$@" ;;
    *) exit 0 ;;
  esac

}

main_enable_multipath_script_source "$@"
