#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: set-default-theme-plymouth
## @Creation date file: 18.04.2021, 02:27:50

[[ -z "${set_default_theme_plymouth_script_source}" ]] && declare -rx set_default_theme_plymouth_script_source="$BASH_SOURCE"

if [[ -z "${set_default_theme_plymouth_script_source_path}" ]]; then
  temp_one="$(dirname ${set_default_theme_plymouth_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx set_default_theme_plymouth_script_source_path="$(pwd)"
  else
    declare -rx set_default_theme_plymouth_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_set_default_theme_plymouth() {

  local install_pkg=(
    'plymouth-kcm'
    # 'plymouth-theme-breeze'
    # 'plymouth-theme-charge'
    # 'plymouth-theme-fade-in'
    # 'plymouth-theme-hot-dog'
    'plymouth-theme-script'
    # 'plymouth-theme-solar'
    # "plymouth-theme-spinfinity"
    # 'plymouth-theme-spinner'
  )

  pm "$@" -- "${install_pkg[@]}"

  sudo plymouth-set-default-theme script
  sudo grub2-mkconfig -o /boot/grub2/grub.cfg
  sudo dracut --force

}

function main_set_default_theme_plymouth_script_source() {

  # printf "Initialise main function of set-default-theme-plymouth script source\n";

  sudo dnf list plymouth-theme*

  install_set_default_theme_plymouth "$@"

}

main_set_default_theme_plymouth_script_source "$@"
