#!/bin/env bash
# -*- coding: utf-8 -*-
#
## @Author: sensor-dream
## @Email: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
## @License: http://www.apache.org/licenses/LICENSE-2.0
## @Site: https://sensor-dream.ru
## @File: nginx-unit
## @Creation date file: 14.04.2021, 22:19:38

[[ -z "${nginx_unit_script_source}" ]] && declare -rx nginx_unit_script_source="$BASH_SOURCE"

if [[ -z "${nginx_unit_script_source_path}" ]]; then
  temp_one="$(dirname ${nginx_unit_script_source})"
  if [[ "${temp_one}" == '.' ]]; then
    declare -rx nginx_unit_script_source_path="$(pwd)"
  else
    declare -rx nginx_unit_script_source_path="${temp_one}"
  fi
fi

if [[ -z "${main_run_script_path}" ]]; then
  declare -rx main_run_script_path="$(pwd)"
  printf "Script runs from path: %s\n" "${main_run_script_path}"
fi

if [[ -z "${main_cfg_script_source}" ]]; then
  check=1
  while [[ "${check}" -eq 1 ]]; do
    if [[ ! -f 'main.cfg' ]]; then
      if [[ "$(pwd)" != "/" ]]; then
        cd ../
      else
        cd ${main_run_script_path}
        check=0
        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
        tput sgr0
        exit 1
      fi
    else
      check=0
      declare -rx main_project_path="$(pwd)"
      . "${main_project_path}/main.cfg" "$@"
      cd "${main_run_script_path}"
    fi
  done
fi

printf "Loading: %s\n" "$(readlink -m ${BASH_SOURCE})"

function install_nginx_unit() {

  local install_pkg=(
    'unit-devel'
    'unit-go'
    'unit-jsc11'
    'unit-jsc8'
    'unit-perl'
    'unit-php'
    'unit-python39'
    'unit-ruby'
    'poppler-utils'
    'wv'
    'libjpeg-turbo'
    'readline'
    'expat'
    'expatpp'
    'openssl'
    'libxml2'
    'libxslt'
  )

  pm "$@" -- "${install_pkg[@]}"

}

function main_nginx_unit_script_source() {

  # printf "Initialise main function of nginx-unit script source\n";

  . "${main_project_path}/manually/repository/nginx-unit"

  install_nginx_unit "$@"

}

main_nginx_unit_script_source "$@"
